### ISSUE TITLE
Use ElasticSearch in Pipelines (instead of SOLR)

### ISSUE THREAD

**Issue by nickdos** [ARGA-Genomes/arga-data#35]
Dave has advised this is possible and would allow ARGA to use the GBIF GraphQL code (Apollo.js) pretty much as-is.

>I’ve got Occurrence only archives indexing into Elastic
its not merged into dev yet
its in this PR: https://github.com/gbif/pipelines/pull/835
On this branch:
https://github.com/gbif/pipelines/tree/60_extended_sensitive_data_pr
not following in `la-pipelines-local.yaml`:
```yaml
# which filesystem to use: local or hdfs
elastic:
  esSchemaPath: /Users/mar759/dev/pipelines/livingatlas/pipelines/src/test/resources/complete-event-pipeline/es-event-core-schema.json
```
